spring.application.name=spring-boot-app
# Web Server Port
server.port=8080

# Aiven Database Connection (SECURED VIA ENVIRONMENT VARIABLES)
spring.datasource.url=${AIVEN_DB_URL}
spring.datasource.username=${AIVEN_DB_USER}
spring.datasource.password=${AIVEN_DB_PASS}

# Hibernate (Auto-create tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Expire sessions after 10 minutes of inactivity
server.servlet.session.timeout=10m