spring.application.name=spring-boot-app
# Web Server Port
server.port=8080

# MS SQL Server Connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=walletdb;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate (Auto-create tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true

# Expire sessions after 10 minutes of inactivity
server.servlet.session.timeout=10m